Aula_MVC_Top/Models/Professor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aula_MVC_Top.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        public int Id_professor { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Idade { get; set; }
        public string Cpf { get; set; }
        public string Senha { get; set; }
    }
}

Aula_MVC_Top/Controllers/ProfessorController.cs
using Aula_MVC_Top.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Aula_MVC_Top.Controllers
{
    public class ProfessorController : Controller
    {
        // GET: Professor
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Create(Professor professor)
        {
            if (!ModelState.IsValid)
            {
                return View(professor);
            }
            else
            {
                List<string> minha_lista = new List<string>();
                if(Session["lista_cpf"] != null)
                {
                    minha_lista = (List<string>)Session["lista_cpf"];
                }
                minha_lista.Add(professor.Cpf);

                Session["lista_cpf"] = minha_lista;
                return View();
                //aqui poderia mandar salvar no banco 
            }
        }

        public ActionResult  validacao(string sexo)
        {

            if(sexo.ToLower() == "m" || sexo.ToUpper() == "M")
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult valida_cpf(string cpf, string email)
        {
            if (Session["lista_cpf"] != null)
            {
                List<string> minha_lista;
                minha_lista = (List<string>)Session["lista_cpf"];
                if (minha_lista.Contains(cpf))
                {
                    return Json(false, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            
        }

        //public ActionResult validaCpf(string cpf)
        //{
        //    List<string> lista_cpf = (List<string>)Session["lista"];

        //    if(lista_cpf !=  null){
        //        foreach (var cpfExistente in lista_cpf)
        //        {
        //            if (cpf == cpfExistente)
        //            {
        //                return Json(false, JsonRequestBehavior.AllowGet);
        //            }
        //        }


        //        lista_cpf.Add(cpf);
        //        Session["lista"] = lista_cpf;
        //    }
        //    return Json(true, JsonRequestBehavior.AllowGet);

        //}
    }
}

Aula_MVC_Top/Views/Professor/Create.cshtml
@model Aula_MVC_Top.Models.Professor
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@*@using(Html.BeginForm("Create", "Professor", FormMethod.Post))*@
<form method="post">
    @Html.LabelFor(x => x.sexo)
    <br />
    @Html.TextBoxFor(x => x.sexo)
    <br />
    @Html.ValidationMessageFor(x => x.sexo)
    <br />

    @Html.LabelFor(x => x.Nome)
    <br />
    @Html.TextBoxFor(x => x.Nome)
    <br />
    @Html.ValidationMessageFor(x => x.Nome)
    <br />

    @Html.LabelFor(x => x.Sobrenome)
    <br />
    @Html.TextBoxFor(x => x.Sobrenome)
    <br />
    @Html.ValidationMessageFor(x => x.Sobrenome)
    <br />

    @Html.LabelFor(x => x.Idade)
    <br />
    @Html.TextBoxFor(x => x.Idade)
    <br />
    @Html.ValidationMessageFor(x => x.Idade)
    <br />

    @Html.LabelFor(x => x.Senha)
    <br />
    @Html.TextBoxFor(x => x.Senha)
    <br />
    @Html.ValidationMessageFor(x => x.Senha)
    <br />

    @Html.LabelFor(x => x.Confirma_Senha)
    <br />
    @Html.TextBoxFor(x => x.Confirma_Senha)
    <br />
    @Html.ValidationMessageFor(x => x.Confirma_Senha)
    <br />

    @Html.LabelFor(x => x.Cpf)
    <br />
    @Html.TextBoxFor(x => x.Cpf)
    <br />
    @Html.ValidationMessageFor(x => x.Cpf)



    <br />
    <input type="submit" value="Salvar" />
</form>



@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")


}

@*, new { @id = "mascara_senha" }
var $j = jQuery.noConflict();

    $j(function () {
    $j("#mascarar_cnpj").mask("99.999.999/9999-99");
    });*@